# Generated by Django 3.2 on 2021-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_honoraryteachers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
