# Generated by Django 3.2 on 2021-09-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20210912_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='date_added',
        ),
    ]
